### ISSUE TITLE
Memory leak while training Resnet50 model

### ISSUE THREAD

**Issue by Yancey1989** [wangkuiyi/gotorch#273]
After 120 iterations, memory usage was increased to 78Gi.

![image](https://user-images.githubusercontent.com/1426912/91811791-a48ee600-ec62-11ea-9e5d-20f86a90f4ce.png)

**Comment by Yancey1989** [comment]
I tried to run the ResNet50 training on CUDA GPU device, the memory increased much slowly -- about 5Gi after 300 iterations, and don't found GPU memory leak. It seems the memory leak happened on dataloader or transformers.

**Comment by wangkuiyi** [comment]
@Yancey1989 I don't understand -- I'd thought that running with or without CUDA, the data loader works the same way; am I right? If so, the fact that memory usage is lower with CUDA than without it shows that the difference is with CUDA, but no the data loader?

**Comment by Yancey1989** [comment]
@wangkuiyi I did some experiment with the fake data to shield the dataloader, and it's easy to reproduce the experiment using PR #285 

## Case1
OS: Mac OSX
libtorch version: [libtorch-macos-1.6.0](https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.6.0.zip)

Conclusion: Memory usage is stable at 3.4G from the begging.

``` bash
$ go run example/resnet/resnet.go
2020/09/02 22:45:45 No CUDA found; CPU only
2020/09/02 22:45:45 train with fake data.
2020/09/02 22:48:47 Train Epoch: 0, Iteration: 10, Memory: 3.40 G
2020/09/02 22:51:50 Train Epoch: 0, Iteration: 20, Memory: 3.38 G
2020/09/02 22:54:55 Train Epoch: 0, Iteration: 30, Memory: 3.38 G
2020/09/02 22:58:05 Train Epoch: 0, Iteration: 40, Memory: 3.38 G
```

## Case2

OS: Linux server + Docker
Libtorch: [libtorch-cxx11-1.6.0-linux-cuda101.zip](https://download.pytorch.org/libtorch/cu101/libtorch-cxx11-abi-shared-with-deps-1.6.0%2Bcu101.zip')

Conclusion: Memory usage is stable at 35G after 170 iterations

Logs:
``` text
root@i85c04105:/work/gotorch# go run example/resnet/resnet.go
2020/09/02 14:45:45 CUDA is valid
2020/09/02 14:45:45 train with fake data.
2020/09/02 14:46:21 Train Epoch: 0, Iteration: 10, Memory: 12.03 G
2020/09/02 14:46:49 Train Epoch: 0, Iteration: 20, Memory: 16.15 G
2020/09/02 14:47:17 Train Epoch: 0, Iteration: 30, Memory: 20.57 G
2020/09/02 14:47:45 Train Epoch: 0, Iteration: 40, Memory: 23.97 G
2020/09/02 14:48:12 Train Epoch: 0, Iteration: 50, Memory: 28.82 G
2020/09/02 14:48:39 Train Epoch: 0, Iteration: 60, Memory: 29.89 G
2020/09/02 14:49:06 Train Epoch: 0, Iteration: 70, Memory: 30.66 G
2020/09/02 14:49:33 Train Epoch: 0, Iteration: 80, Memory: 30.97 G
2020/09/02 14:49:59 Train Epoch: 0, Iteration: 90, Memory: 31.44 G
2020/09/02 14:50:26 Train Epoch: 0, Iteration: 100, Memory: 32.06 G
2020/09/02 14:50:52 Train Epoch: 0, Iteration: 110, Memory: 32.82 G
2020/09/02 14:51:19 Train Epoch: 0, Iteration: 120, Memory: 33.01 G
2020/09/02 14:51:46 Train Epoch: 0, Iteration: 130, Memory: 33.47 G
2020/09/02 14:52:13 Train Epoch: 0, Iteration: 140, Memory: 33.90 G
2020/09/02 14:52:39 Train Epoch: 0, Iteration: 150, Memory: 33.84 G
2020/09/02 14:53:06 Train Epoch: 0, Iteration: 160, Memory: 34.41 G
2020/09/02 14:53:33 Train Epoch: 0, Iteration: 170, Memory: 34.76 G
2020/09/02 14:53:59 Train Epoch: 0, Iteration: 180, Memory: 35.48 G
2020/09/02 14:54:26 Train Epoch: 0, Iteration: 190, Memory: 34.91 G
2020/09/02 14:54:54 Train Epoch: 0, Iteration: 200, Memory: 34.55 G
2020/09/02 14:55:20 Train Epoch: 0, Iteration: 210, Memory: 34.96 G
2020/09/02 14:55:47 Train Epoch: 0, Iteration: 220, Memory: 35.02 G
2020/09/02 14:56:13 Train Epoch: 0, Iteration: 230, Memory: 34.86 G
2020/09/02 14:56:40 Train Epoch: 0, Iteration: 240, Memory: 35.44 G
2020/09/02 14:57:07 Train Epoch: 0, Iteration: 250, Memory: 35.42 G
2020/09/02 14:57:34 Train Epoch: 0, Iteration: 260, Memory: 35.09 G
2020/09/02 14:58:01 Train Epoch: 0, Iteration: 270, Memory: 35.36 G
2020/09/02 14:58:28 Train Epoch: 0, Iteration: 280, Memory: 35.70 G
```

**Comment by shendiaomo** [comment]
`Resnet50` works well on MacBook and Linux with CUDA. **At the moment, the problem seems to occur only on Linux with a CPU-only `libtorch 1.6.0`**

After many investigations, I found that the problem is likely caused by OpenMP or MKLDNN. In my environment (Docker on MacBook), the following setting makes `resnet50` work, but the process has a footprint of about 6g that's growing slowly.

```bash
OMP_NUM_THREADS=1 taskset -c 0 go run resnet.go -epochs=100
```

The root cause is still under investigation, we may ask the libtorch people for more information.

**Comment by shendiaomo** [comment]
> `Resnet50` works well on MacBook and Linux with CUDA. **At the moment, the problem seems to occur only on Linux with a CPU-only `libtorch 1.6.0`**
> 
> After many investigations, I found that the problem is likely caused by OpenMP or MKLDNN. In my environment (Docker on MacBook), the following setting makes `resnet50` work, but the process has a footprint of about 6g that's growing slowly.
> 
> ```shell
> OMP_NUM_THREADS=1 taskset -c 0 go run resnet.go -epochs=100
> ```
> 
> The root cause is still under investigation, we may ask the libtorch people for more information.

There're no severe leaks in the GoTorch code base. The reason of the issue is that `libtorch` creates too many threads (150+ in a Docker container (12 cores) on my MacBook), `libtorch` may use thread-local storage for caching temporary data of convolution operation, therefore, such amount of threads will certainly consume lots of RAM.

The solution is to disable processor migration via setting `OMP_PROC_BIND=TRUE`. After that, there would be only 40+ threads.  It is still under investigation why OpenMP or MKLDNN creates more threads when migration enabled.

**Comment by shendiaomo** [comment]
> > `Resnet50` works well on MacBook and Linux with CUDA. **At the moment, the problem seems to occur only on Linux with a CPU-only `libtorch 1.6.0`**
> > After many investigations, I found that the problem is likely caused by OpenMP or MKLDNN. In my environment (Docker on MacBook), the following setting makes `resnet50` work, but the process has a footprint of about 6g that's growing slowly.
> > ```shell
> > OMP_NUM_THREADS=1 taskset -c 0 go run resnet.go -epochs=100
> > ```
> > 
> > 
> > The root cause is still under investigation, we may ask the libtorch people for more information.
> 
> There're no severe leaks in the GoTorch code base. The reason of the issue is that `libtorch` creates too many threads (150+ in a Docker container (12 cores) on my MacBook), `libtorch` may use thread-local storage for caching temporary data of convolution operation, therefore, such amount of threads will certainly consume lots of RAM.
> 
> On the contrary, the Mac version of `libtorch` uses only a single thread to train, that's why Resnet50 has a small footprint of 2G.
> 
> The solution to the Linux version is to disable processor migration via setting `OMP_PROC_BIND=TRUE`. After that, there would be only 40+ threads and occupies about 7G. The training program can run steadily on a container that has RAM more than 8G.
> 
> It is still under investigation why OpenMP or MKLDNN creates more threads when migration enabled.

I've found the root cause, which is neither `OpenMP` nor `libtorch`.

The problem is caused by Cgo: each blocking `Cgo` call may occupy a system thread. The Go runtime creates many threads for `Cgo` calls, each of which may migrate from one system thread to another. After running for some time, each thread created by the go runtime has a copy of the TLS caches of libtorch, thus occupying all the RAM.

Adding a call to `runtime.LockOSThread` in an `init` function solves the problem via locking all `Cgo` calls to a fixed thread.

Now in my Docker container, the Go version of Resnet has a footprint of about 4G, only a bit larger than the C++ equivalent. Try this and feedback for further improvement @Yancey1989 .

**Comment by wangkuiyi** [comment]
@shendiaomo I am trying to understand this -- what kind of Cgo calls could block and cause the migration of the caller goourtine to another OS threads?
